### ISSUE TITLE
Command "clone" results in an error on a Windows7 machine... 

### ISSUE THREAD

**Issue by sohail** [maryrosecook/gitlet#13]
Hi, command **E:\Work\gitlet clone a b** resulted in error message...

Error: cannot lock the ref refs/remotes/origin\master

And few changes made the command work...

```javascript 
  // **toRemoteRef()** converts `remote` and branch name `name` into a
  // qualified remote branch ref.
  toRemoteRef: function(remote, name) {
    if (process.platform == "win32") {      
      return "refs/remotes/" + remote + "/" + name;
    } else {
      return  "refs/remotes/" + remote + nodePath.sep + name;
    }    
  },

**Comment by maryrosecook** [comment]
Thanks a lot for this.  Coincidentally I spotted this yesterday and fixed it.  If you pull, you should get the fix.  Thanks again!
