### ISSUE TITLE
A question about Github implementation

### ISSUE THREAD

**Issue by yehia67** [maryrosecook/gitlet#24]
Hi,
I have a question and I don't know where to ask. I am going to make a website exactly like GitHub but It will be decentralized (Implement it using Blockchain). But I don't know how to link between the local .git directory to a website? And do you know any library,npm package, tool...etc that implement all git functions? (And I could use it in a project for implementing Github)

**Comment by maryrosecook** [comment]
Hiya! You mean how to show the contents of a git repo on a site?

I believe there are some JS implementations of Git, but I'm not really up to date on how feature complete they are, and which ones are the best.  If you Google for it, you'll hopefully find the best one.

Good luck!
