### ISSUE TITLE
Compare to dugite?

### ISSUE THREAD

**Issue by linonetwo** [maryrosecook/gitlet#27]
https://github.com/desktop/dugite is a git binding that used in GithubDesktop, will this be a JS replacement for dugite?

Does gitlet support all features that GithubDesktop or other git client GUI needs?

PS I'm creating a Git GUI, and is looking at gitlet and dugite.

**Comment by maryrosecook** [comment]
I'm afraid gitlet isn't compatible with any other git clients.  It's just a toy implementation to demonstrate how git works.

**Comment by linonetwo** [comment]
okay，seems there is no any production ready js git impl currently, all toys, sad...

**Comment by linonetwo** [comment]
I see, I can use https://github.com/isomorphic-git/isomorphic-git
