### ISSUE TITLE
A call to function update_index, fails with error message... on a Windows7 machine.

### ISSUE THREAD

**Issue by sohail** [maryrosecook/gitlet#4]
I'm using node.js version 0.10.31 on a Windows7 machine and I'm getting error....  

" { [Error: ENOENT, no such file or directory 'E:\E:'] errno: 34, code: 'ENOENT', path: 'E:\\E:', syscall: 'mkdir' } " 

when I try to add a file to index such as... E:\Work\a\gitlet add b.txt

Thanks

**Comment by maryrosecook** [comment]
Thanks a lot for reporting this.  Would you mind checking out the branch `stack-trace-top-level-error` and running the code again and sending me the stack trace that is printed out? (I don't have a Windows machine here, I'm afraid.)  Thanks a lot!

**Comment by sohail** [comment]
Hi, the stack-trace of the issue...

Error: ENOENT, no such file or directory 'E:\E:'
    
    at Object.fs.mkdirSync (fs.js:653:18)
    
    at C:\Users\Sohail\AppData\Roaming\npm\node_modules\gitlet\gitlet.js:1754:14
    
    at Array.forEach (native)
    
    at Object.files.writeFilesFromTree (C:\Users\Sohail\AppData\Roaming\npm\node_modules\gitlet\gitlet.js:1748:23)
    
    at Object.files.write (C:\Users\Sohail\AppData\Roaming\npm\node_modules\gitlet\gitlet.js:1741:11)
    
    at Object.objects.write (C:\Users\Sohail\AppData\Roaming\npm\node_modules\gitlet\gitlet.js:1004:11)
    
    at Object.index.writeEntry (C:\Users\Sohail\AppData\Roaming\npm\node_modules\gitlet\gitlet.js:1174:43)
    
    at Object.index.writeAdd (C:\Users\Sohail\AppData\Roaming\npm\node_modules\gitlet\gitlet.js:1161:11)
    
    at Object.module.exports.update_index (C:\Users\Sohail\AppData\Roaming\npm\node_modules\gitlet\gitlet.js:752:13)
    
    at C:\Users\Sohail\AppData\Roaming\npm\node_modules\gitlet\gitlet.js:149:47

**Comment by sohail** [comment]
Hi, sort of bit more feedback...

```javascript   
writeFilesFromTree: function(tree, prefix) {      
     if (process.platform == "win32") { 
       var path = "";
       var key = [];
       while (1) {
         key = Object.keys(tree);
         if (util.isString(tree[key])) {
           break;  
         }
         tree = tree[key];
         path = path + key[0];
         if (!fs.existsSync(path)) { 
           fs.mkdirSync(path, "777");         
         }
         path = nodePath.join(path, prefix);        
       }                  
       /* We are out of the loop as we reached the filecontent part of the tree */
       path = path + key[0];
       fs.writeFileSync(path, tree[key]);       
     } else {
       /* Here deal with non Windows OSs... */  
     }            
   },

**Comment by maryrosecook** [comment]
Thanks a lot for your help with this.  Would you mind checking out the branch `fix-windows-root-directory` and testing using that code? Thanks again!

**Comment by sohail** [comment]
Hi, it did not work and error message was...

Error: ENOENT, no such file or directory 'E:**\E:**'

and cause of the error is the last **BOLD** portion of the above error message. The statement...
**var path = nodePath.join(prefix, name);** of function **writeFilesFromTree: function(tree, prefix)** is putting the OS-CORRECT path-seperator but, it is placing it before the drive letter **E:**.  

This is what I actually wanted to show you, in the bit modified version of your function **writeFilesFromTree: function(tree, prefix)** which I posted above in my last message.

**Comment by maryrosecook** [comment]
I've just pushed a ton of fixes for Gitlet pathing on Windows.  I think the `gitlet add` problem should be fixed.  Would you mind pulling master the running the command again? If it works, would you mind running the tests, too? Thanks so much for all your help!

**Comment by sohail** [comment]
Hi, new commits are working, "add" and all other commands/options worked without errors. Running tests now...

**Comment by maryrosecook** [comment]
Great! Let me know!

**Comment by sohail** [comment]
I'm really sorry for the badly formatted text, I tried but was not able to put it in more format correct way.  

```
> gitlet@0.1.12 test E:\Work\gitlet

> jasmine-node spec


..................................................F..FF......................................................................................................................................................................................................................................


Failures:

  1) clone successful clone should set origin of new repo to remote
   
            Message:
     Expected '  url = ..\repo1' to equal '  url = ../repo1'.
   
            Stacktrace:
     
              Error: Expected '  url = ..\repo1' to equal '  url = ../repo1'.
    
             at null.<anonymous> (E:\Work\gitlet\spec\clone.spec.js:63:10)

  

           2) clone successful clone should set master to remote master hash
   
            Message:
     Expected '76deb86b' to equal '17a11ad4'.
   
            Stacktrace:
     
              Error: Expected '76deb86b' to equal '17a11ad4'.
    
             at Object.module.exports.expectFile (E:\Work\gitlet\spec\test-util.js:8:43)
    
             at null.<anonymous> (E:\Work\gitlet\spec\clone.spec.js:95:16)


  
           3) clone successful clone should write remote master hash index
   
            Message:
     Expected '1a\filea' to equal '1a/filea'.
   
            Stacktrace:
     
              Error: Expected '1a\filea' to equal '1a/filea'.
    
             at null.<anonymous> (E:\Work\gitlet\spec\clone.spec.js:107:40)



Finished in 1605.983 seconds
285 tests, 787 assertions, 3 failures, 0 skipped


285 tests, 787 assertions, 3 failures, 0 skipped
```

**Comment by maryrosecook** [comment]
Thanks a lot for that.  I made a ton of changes to the tests to make paths independent of platform.  It seems like I missed a few.  I've updated them.  Would you mind running the tests once again? Thanks so much.

**Comment by maryrosecook** [comment]
(Please pull master before you run the tests!)

**Comment by sohail** [comment]
pulled master and conducting tests.

**Comment by sohail** [comment]
```
> gitlet@0.1.13 test 
E:\Work\gitlet
> jasmine-node spec
.............................................................................................................................................................................................................................................................................................
Finished in 1738.51 seconds
285 tests, 787 assertions, 0 failures, 0 skipped



```

**Comment by maryrosecook** [comment]
WOOHOO! Thanks so much for all your help!
