### ISSUE TITLE
Why the .gitlet directory?

### ISSUE THREAD

**Issue by piranna** [maryrosecook/gitlet#5]
Reading your docs I've seen [you are using a non-standard ```.gitlet``` directory](If the repository is not bare, put the directories inside the .gitlet directory) instead of the standard ```.git``` one. Why is this? There could be some compatibilities issues? I'm asking this because we are thinking we could use ```gitlet``` at [NodeOS](https://github.com/NodeOS/NodeOS/issues/67)... :-)

**Comment by maryrosecook** [comment]
Ah, that is very flattering that you would consider Gitlet.  However, it's not suitable for version control.  It's only meant as a demonstration of how Git works under the covers.  It is definitely not robust enough for real work.

**Comment by piranna** [comment]
You are welcome :-) But it would not be used for production-grade version control but mostly as ```git``` command replacement for ```npm```, so it could be able to use git repositories as dependencies (mainly downloads). Since it's able to do clone, it should work. Do you think is this feasable with gitlet? Does it has support for network protocols? In your examples you only do clone from another local folder in your machine...

**Comment by maryrosecook** [comment]
I’m afraid it doesn’t support network protocols for inter-repository communication, so it’s really not feasible for use over the network.

**Comment by piranna** [comment]
> I’m afraid it doesn’t support network protocols for inter-repository communication, so it’s really not feasible for use over the network.

It's sad to heard that :-( Anyway, I invite you to join the discussion
(https://github.com/NodeOS/NodeOS/issues/67#issuecomment-71391565),
seems the git cli tool requeriments needed by npm are fairly minimal
and gitlet is more advanced on this point that js-git from a UI
perspective, so you could help us to combine both and create a
pure-Javascript git client for NodeOS :-)


-- 
"Si quieres viajar alrededor del mundo y ser invitado a hablar en un
monton de sitios diferentes, simplemente escribe un sistema operativo
Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by maryrosecook** [comment]
I'm afraid that's not the direction that I want to take Gitlet.  It's meant as a project to learn how Git works, not a Git replacement.

**Comment by piranna** [comment]
Ok, anyway good job ;-)

2015-01-27 18:12 GMT+01:00 Mary Rose Cook <notifications@github.com>:

> I'm afraid that's not the direction that I want to take Gitlet. It's meant
> as a project to learn how Git works, not a Git replacement.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maryrosecook/gitlet/issues/5#issuecomment-71686473>.
>



-- 
"Si quieres viajar alrededor del mundo y ser invitado a hablar en un monton
de sitios diferentes, simplemente escribe un sistema operativo Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by maryrosecook** [comment]
Thanks!

--
http://maryrosecook.com

**Comment by piranna** [comment]
You are welcome :-)

2015-01-28 13:47 GMT+01:00 Mary Rose Cook <notifications@github.com>:

> Thanks!
>
> --
> http://maryrosecook.com
>
> > On 28 Jan 2015, at 06:34, Jesús Leganés Combarro <
> notifications@github.com> wrote:
> >
> > Ok, anyway good job ;-)
> >
> > 2015-01-27 18:12 GMT+01:00 Mary Rose Cook <notifications@github.com>:
> >
> > > I'm afraid that's not the direction that I want to take Gitlet. It's
> meant
> > > as a project to learn how Git works, not a Git replacement.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/maryrosecook/gitlet/issues/5#issuecomment-71686473>.
>
> > >
> >
> >
> >
> > --
> > "Si quieres viajar alrededor del mundo y ser invitado a hablar en un
> monton
> > de sitios diferentes, simplemente escribe un sistema operativo Unix."
> > – Linus Tordvals, creador del sistema operativo Linux
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maryrosecook/gitlet/issues/5#issuecomment-71829506>.
>



-- 
"Si quieres viajar alrededor del mundo y ser invitado a hablar en un monton
de sitios diferentes, simplemente escribe un sistema operativo Unix."
– Linus Tordvals, creador del sistema operativo Linux
