### ISSUE TITLE
Support npm

### ISSUE THREAD

**Issue by secrettriangle** [maryrosecook/gitlet#9]
With npm support, gitlet could be used for NodeOS. The following features are missing from gitlet which prevent it from being used with npm, and as an extension NodeOS:

- [ ] #8 Implement `git config --get remote.<remote>.url`

Collaborators, please feel free to update this list as you see fit!

**Comment by maryrosecook** [comment]
Hiya.  I'm afraid that I think this is outside the scope of Gitlet.  To keep the code short and readable, I've tried to only support options that demonstrate fundamental elements of Git's design.  I don't think this option passes that test.  Sorry to not be more helpful.

**Comment by secrettriangle** [comment]
Fair enough. Would you be willing to accept a pull request that helps move gitlet closer to npm compatibility?

**Comment by maryrosecook** [comment]
What would the pull request contain? Thanks a lot.
